### ISSUE TITLE
INCOMING/OUTGOING seems to be ignored

### ISSUE THREAD

**Issue by tgbugs** [OpenKnowledgeSpace/KnowledgeSpace#70]
Testing delineatedBy vs delineates it seems that the relations panel includes edges that are BOTH instead of just INCOMING or OUTGOING.

**Comment by wawong** [comment]
Tom, can you send me a URL as an example? Thanks!

**Comment by tgbugs** [comment]
https://knowledge-space.org/wiki/UBERON:0001897

Right now it is hard to see what is going on, but if you add

``` 
        {
            "name":"Delineates",
            "value":"http://uri.interlex.org/base/delineates",
            "direction":"in-coming"
        }

```

You will see that the "in-coming" and "out-going" don't seem to filter correctly.

**Comment by wawong** [comment]
Hi Tom,

I want to compare https://knowledge-space.org/wiki/UBERON:0001897 with 
http://kaa.neuinfo.org/wiki/UBERON:0001897 (I updated the source code on kaa).

If you look at http://matrix.neuinfo.org:9000/scigraph/graph/neighbors/UBERON:0001897?depth=10&relationshipType=subClassOf&blankNodes=false&direction=INCOMING&project=%2A

"sub": "UBERON:0001897",
      "obj": "UBERON:0002709",
      "pred": "http://www.obofoundry.org/ro/ro.owl#has_proper_part",
      "meta": {
        
      }

{"sub":"MBA:549","obj":"UBERON:0001897","pred":"http://uri.interlex.org/base/delineates","meta":{}},

If the version in kaa is correct, then it doesn't really matter whether the property is in-coming or out-going because we always rely on the subject and object for direction.

**Comment by wawong** [comment]
Correcting the matrix link in the previous ticket:
http://matrix.neuinfo.org:9000/scigraph/graph/neighbors/UBERON:0001897?depth=1&blankNodes=false&direction=BOTH&project=%2A

**Comment by jgrethe** [comment]
One side question: what is with the "wiki" in the URLs?

**Comment by tgbugs** [comment]
I was looking for a prefix for all the entity pages, and even though it sort of breaks the expectations of 'wikiness' I figured that since we are masquerading as an encyclopedia it was a reasonably choice. If there are other ideas we can definitely change it. Some thoughts are `entities`, `enc`, `ents`, `entries`, `classes`, etc. but none seem to fit to me.
